server:
  port: 2443
spring:
  application:
    name: data-service
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: MySuperStrongPassword
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1443/eureka}
  instance:
    preferIpAddress: true