spring:
  application:
    name: api-gateway-service
  datasource:
    url:  jdbc:mysql://localhost:3306/bms?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: MySuperStrongPassword
    data: classpath:data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
server:
  port: 443
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1443/eureka}
  instance:
    preferIpAddress: true
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 36000000